#!/bin/bash
set -eo pipefail

readonly APPSDIR="$HOME"/apps
readonly CONFIGDIR="$HOME"/.config

prerequisites() {
	echo "dotconfigs: checking pre-requisite stuff before moving on..."
	if ! [[ -d "$APPSDIR" ]]; then
		mkdir -p "$APPSDIR"
	fi

	if ! [[ -d "$CONFIGDIR" ]]; then
		mkdir -p "$CONFIGDIR"
	fi
}

install_nvim() {
	sudo apt install nvim
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	cp -r "$WORKDIR"/config/nvim "$CONFIGDIR"
	echo "dotconfigs: run \":PlugInstall\" in neovim"
	echo "dotconfigs: neovim has been installed!"
}

install_rust() {
	echo "dotconfigs: installing Rust..."
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	return 0
}

install_alacritty() {
	echo "dotconfigs: installing alacritty..."
	if ! [[ -x "$(command -v cargo)" ]]; then
		install_rust
	fi

	if [[ -x "$(command -v alacritty)" ]]; then
		echo "dotconfigs: alacritty is already installed!"
		return 0
	fi

	sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
		libxcb-xfixes0-dev libxkbcommon-dev python3

	rustup override set stable && rustup update stable

	git clone https://github.com/alacritty/alacritty.git "$APPSDIR"/alacritty
	cd "$APPSDIR"/alacritty && cargo build --release && \
		sudo tic -xe alacritty,alacritty-direct extra/alacritty.info &&\
		sudo cp target/release/alacritty /usr/local/bin &&\
		sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg &&\
		sudo desktop-file-install extra/linux/Alacritty.desktop &&\
		sudo update-desktop-database

	if [[ -x "$(command -v alacritty)" ]]; then
		echo "dotconfigs: alacritty has been installed!"
		return 0
	else
		echo "dotconfigs: alacritty installation has failed, check the output" >&2
		return 1
	fi
}

install_tmux() {
	sudo apt install tmux
}

sync_files() {
	echo "dotconfigs: syncing system configuration to repository..."
	cp "$CONFIGDIR"/alacritty/alacritty.yml ./config/alacritty
	cp "$CONFIGDIR"/nvim/init.vim ./config/nvim
	cp "$HOME"/.zshrc ./zsh
}

main() {
	declare action="$1" component="$2"

	case "$action" in
		"install")
			case "$component" in
				"rust")
					prerequisites
					install_rust
					;;
				"alacritty")
					prerequisites
					install_alacritty
					;;
				"nvim")
					prerequisites
					install_nvim
					;;
				"tmux")
					prerequisites
					install_tmux
					;;
				"all")
					prerequisites
					install_tmux
					install_nvim
					install_rust
					install_alacritty
					;;
				*)
					echo "dotconfigs: unknown component to install" >&2
					return 1
			esac
			;;
		"sync")
			sync_files
			return 0
			;;
		*)
			echo "dotconfigs: unknown command" >&2
			return 1
			;;
	esac
}

main "$@"
